### PR TITLE
Update filenames to reflect new test ID format

### PR DESCRIPTION
**Pull request by kengdoj**
Updated test ID Format: [Baseline Test ID#]-[test step #]-[pass/fail/dna]-[reference #]

### CODE REVIEW

**Review by akingkci — APPROVED** [review]
This is in line with my understanding that the revised test case id is generated based on the following logic:

1. "06.1" points to baseline test "6.1 Test Procedure for Meaningful Images:
2. "-" hyphen separator
3. "1" points to the appropriate baseline test step
4. "-" hyphen separator
5. "fail" expected outcome of this test case
6. "-" hyphen separator
7. "1" points to an incrementor that can be any value that results in a unique composite test case id

**Comment by kengdoj** [comment]
Thanks for the review, @akingkci!

These were updates only to the test files filenames. Similar updates are needed for the test case "TC" filenames and for the link in the TC to the test files. I'll add a separate issue for that.

**Comment by akingkci** [comment]
Got it 😊

**Review by drewnielson — APPROVED** [review]
Looks good to me too. I think we'll need to come back and update some links but that can be a separate update.

**Pull request merged**
