### PR TITLE
Update TC05.1-1-1-fail

### PR DESCRIPTION
**Pull request by kengdoj**
- updated links to test case files
- removed Baseline Test info since it's also in the table
- changed table numbering to match Baseline Test instructions. 
- changed table heading scope

**Question** - the table's `<caption>` appears at the bottom of the table. I'd like it to show above the table. Where to change that?

Issue #57

### CODE REVIEW

**Review by akingkci — COMMENTED** [review]
I'm good with the removal of the "Test Instruction" wording from the test case and basically just referring to it via "Test Instruction 1"  But as I look at the overall template format and thinking about outside contributors and also others understanding the flow of the test case wording, should we align better with the baseline regarding the sections "Identify Content" vs. "Test instructions"?.  

For example, in the test case document heading "Test steps", we have entries that are really "Identify Content" activity.  Do we want to make a separate section in the test case, before we get into the test instruction test steps, with a heading of "Identify Content" for these identify content activities and then get into the section that addresses the test instructions and test steps - as is the order in the baseline? 

Regarding the current test case document heading of "Test steps", do we want to align with the baseline and relabel that heading as "Test Instructions" and then in the existing table in that section, keep the heading as "test steps" to record the applicable test steps? 

It seems that would be easier to follow and to align with the baseline.

**Comment by kengdoj** [comment]
I agree with your suggestions, @akingkci. I'll make some more edits:

- [ ] Separate Identify Content from Test Steps
- [ ] Rename Test Steps to Test Instructions

Converting this PR to draft

**Comment by drewnielson** [comment]
Also agree with Alan's points on Identify Content vs. Test Instructions

>

**Comment by kengdoj** [comment]
In the meantime, any ideas for this question -

the table's `<caption>` appears at the bottom of the table. I'd like it to show above the table. Where to change that?

**Comment by drewnielson** [comment]
Sorry, which caption? for which table?

**Comment by akingkci** [comment]
Kathy,

Can you send a screen shot of what you are seeing? In my IDE, the caption is showing at the top of the table if you’re talking about the caption below:

“Description of the test case's results for each part of the Baseline Test. Asterisk (*) indicates the test instruction for which this test case was developed.”

**Comment by kengdoj** [comment]
maybe it's just appearing at the bottom of the table for me:

image

**Comment by drewnielson** [comment]
No, sorry - I see what you mean. Just need to add a style to move the caption to the top of the table:
`<caption style="caption-side:top;">`

**Comment by akingkci** [comment]
Yep, I see now too. Something in the bootstrap style that is doing it. Probably an ::after or ::before setting…

**Comment by drewnielson** [comment]
If we want to change it for all of the tables in the Test Steps, then probably best that we just create a new class for the Test Steps table and move the caption to the top for the class.

**Comment by akingkci** [comment]
Andrew,

I believe a quick way to address this is to comment out the property below I’ve highlighted in red in the existing bootstrap CSS style  it will address the issue:

caption {
  padding-top: 0.75rem;
  padding-bottom: 0.75rem;
  color: #6c757d;
  text-align: left;
 caption-side: bottom;
}

**Comment by drewnielson** [comment]
Sure, that's fine if we want to modify for all tables, but I think I would prefer to keep captions at the bottom of the table for most tables. If we only want to have captions at the top of the table for the Test Steps tables then we'll probably want to keep the bootstrap style as is and create a class for just the Test Steps tables.

**Comment by akingkci** [comment]
Yep, agreed if captions are to be at the bottom for most tables.

**Comment by akingkci** [comment]
I have a window of about 30min I can spare – would you like me to create a new style and hand it off to Kathy or did you want to take care of that?

**Comment by drewnielson** [comment]
Actually, Kathy and I just chatted - we're going to walk through it together just after the Baseline WG meeting. We'll just work it in with this pull request.

**Comment by akingkci** [comment]
Awesome.

**Comment by drewnielson** [comment]
Talked with Kathy some more - preference is to have captions at the top for all tables after all. Ended up making the change to the bootstrap stylesheet just as you recommended, Alan.

**Comment by kengdoj** [comment]
@akingkci - would you mind looking at the TC file? Starting on line 152, I tried to create a script that would automatically load the content of a div from the test file so it wouldn't require a copy and paste to display the code in the test case. It's not working and I can't figure out why. 

I also modified the test file to remove the reload. I just replaced the text instead.

**Comment by akingkci** [comment]
Hey Kathy,

Looks like you’re practically there.  See attached an example I mocked up. There are 2 files: testcase.html and testfile.html.  The testcase.html code is very similar to yours so just pass to the “.load()” function the test file you want to copy into the testcase.html file to make it work – just like your code.  You will need to run my example files on a file server to have the JavaScript runt correctly for the div copy functionality.

I also included in the same testcase.html file an example of copying the testcase to an iFrame instead of a <div>. You might want to at least consider that approach because there may be issues loading some code examples in the future that might not display completely or correctly when trying to display them within an existing HTML document. One of the reasons iFrame came to be was to address issues like that.  Just a thought…

**Comment by kengdoj** [comment]
@drewnielson and @akingkci -

I used fetch() to get the code to display in a textarea so it wouldn't execute. I don't want the entire code to show, just an ID, so more work to do.

See [preview](http://htmlpreview.github.io/?https://github.com/Section508Coordinators/baselinealignment/blob/kengdoj-updateTClinks/docs/testcases/TC05.1-1-fail-1.html)

**Review by drewnielson — APPROVED** [review]
OK to merge in draft

**Pull request merged**
