### PR TITLE
Up load new test case file TC14.1-all-1 for review

### PR DESCRIPTION
**Pull request by vprentice**
Pass Test Case example for 1st review.

### CODE REVIEW

**Review by kengdoj — DISMISSED** [review]
Good start on the test case file! Would be very helpful if you include the related test file and testcases.md updates in your pull request so the bundle can be reviewed together.

**Comment by vprentice** [comment]
Please confirm pull request for review of new test case 14.1-2-Fail-1

**Comment by vprentice** [comment]
Up loaded new test case and file TC14.1-all-dna-1 for review,

**Comment by drewnielson** [comment]
This pull request is superseded by #129

**Pull request closed without merging**
